### ISSUE TITLE
Issue opening menu to see live streams

### ISSUE THREAD

**Issue by CodyRude** [buzz/twitch-indicator#10]
I'm having an issue where menu doesn't pop up a list of live streams for me to select. I can see there are x number of streams live, but it doesn't pop up the list of live streams when I mouse over it. I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twitch_indicator/indicator.py", line 77, in add_streams_menu
    if enabled_channel_ids[stream["id"]]:
KeyError: 22253819
```

I tried to poke around a bit, but it's been a while and I can't seem to get it to run directly from my cloned repo

I forgot to add:
Archlinux, python3.10

**Comment by AlejandroC90** [comment]
Same thing happening to me
ArchLinux
Python 3.10.2
