### ISSUE TITLE
Twitch API ending

### ISSUE THREAD

**Issue by LizzieA69** [buzz/twitch-indicator#11]
Please update this app to the new Twitch API. The Twitch V5 API will end February 28, 2022. Info about the V5 API shutdown is in the Twitch blog located here: https://blog.twitch.tv/de-de/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

**Comment by buzz** [comment]
Looking at the official [v5 to Twitch API Migration Guide](https://dev.twitch.tv/docs/api/migration) the only substantial change is how authentication works. We already migrated to [OAuth tokens in 2020](https://github.com/buzz/twitch-indicator/commit/abb6d50a5ab473b4f04de153980ff2a6bc04a3cb). 

Did you identify any other issues in the codebase?

**Comment by LizzieA69** [comment]
I have found no other issues with the app and I'm glad to hear it will continue to work after February 28
