### ISSUE TITLE
No longer working (auth failure?)

### ISSUE THREAD

**Issue by avahe-kellenberger** [buzz/twitch-indicator#20]
This software worked in the past, but now when I try to authorize its use through twitch, nothing happens.

When I click "Authorize" I am directed to a URL (like https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=lp42a3ot0vosrva84upd4up077f6vd&state=JuRlKNBxIlD5OM1OFDSxHCbJ0qyMgk&redirect_uri=twitch-indicator-auth%3A%2F%2Fauthorize&scope=user%3Aread%3Afollows#)

but nothing comes of it, and the application won't actually launch

**Comment by buzz** [comment]
I just re-authorized recently. It should work. It opens a browser window and the application reads the token. Not much I can do without knowing any specifics...

**Comment by avahe-kellenberger** [comment]
I just see this: 
![image](https://github.com/buzz/twitch-indicator/assets/34498340/4cbdd72f-a2d9-464b-b3a1-db4b40bbc652)


I also have `twitch-indicator-auth` but am not sure how I could/should use it

**Comment by buzz** [comment]
Then the application should read the token and work properly.

If it's not, you should start it on the command line and post the output here. There should be some kind of error message.

**Comment by avahe-kellenberger** [comment]
There's no output in the terminal, it just opens the same URL again in my browser. Which part of the url would be the token, or should I just provide the entire url?

I'm currently just supplying the whole url, like:
`twitch-indicator-auth 'https://...'`

**Comment by buzz** [comment]
The process is fully automatic. You only need to authorize the app on the Twitch website which should open automatically when starting the auth process. The twitch website then calls [twitch-indicator-auth](https://github.com/buzz/twitch-indicator/blob/main/twitch_indicator/auth_script.py), which passes the token to the app using a unix socket.

For this to work, you will need to have [this desktop entry](https://github.com/buzz/twitch-indicator/blob/main/data/twitch-indicator-auth.desktop) installed. This should happen automatically when using AUR. It registers a custom handler `x-scheme-handler/twitch-indicator-auth` which allows the browser to call the auth script.

**Comment by avahe-kellenberger** [comment]
So is it just invoking `twitch-indicator-auth` with the entire URL as the first argument to the program? It seems to just be a circular loop of opening a tab, asking to open `twitch-indicator-auth`, which opens a new tab...

**Comment by avahe-kellenberger** [comment]
https://github.com/buzz/twitch-indicator/assets/34498340/96558f0a-da10-4d62-82eb-6feb97199270

**Comment by buzz** [comment]
> So is it just invoking `twitch-indicator-auth` with the entire URL as the first argument to the program? It seems to just be a circular loop of opening a tab, asking to open `twitch-indicator-auth`, which opens a new tab...

Yes. You can see [here](https://github.com/buzz/twitch-indicator/blob/1fc78495066fd1da9968d8d736a8e0e349416a88/twitch_indicator/auth.py#L75) how such an URL coming from Twitch is parsed.

It seems, `twitch-indicator-auth` is never called in your case. Maybe your Desktop environment doesn't support [mime-apps-spec](https://www.freedesktop.org/wiki/Specifications/mime-apps-spec/) and/or [desktop-entry-spec](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) properly?

**Comment by avahe-kellenberger** [comment]
Perhaps, but invoking it directly with the URL doesn't seem to work either

**Comment by buzz** [comment]
@avahe-kellenberger I just released v1.7. It has an alternative auth flow using a local web server instead of mime-apps-spec/desktop-entry-spec. Could you try with this version?

**Comment by avahe-kellenberger** [comment]
It's works! @buzz thanks, really happy to have this application working again.
