### ISSUE TITLE
List items too large and "Check now" button missing

### ISSUE THREAD

**Issue by 5ucur** [buzz/twitch-indicator#21]
Updated the program today. The behaviour as illustrated in the screenshot occurs. The screenshot's height is the height of the whole screen. I don't have a screenshot of the old version, but the list items were easily at least half the height of the current ones.
Also, the option to check immediately for any streams is missing.
I'm on Arch Linux `6.6.30-2-lts` with the currently latest version of Twitch Indicator that is present on the AUR (there listed as 1.7-1).
![2024-05-16_18-19_a](https://github.com/buzz/twitch-indicator/assets/28569802/c4cb2c98-dbe4-420c-85f8-4018e2e6a238)

**Comment by buzz** [comment]
> I don't have a screenshot of the old version, but the list items were easily at least half the height of the current ones.

Unfortunately your list is blurred. So, I don't see what you mean or if anything is off.
The icons should be 32x32 pixels in size. They might have been smaller in previous versions which is more appropriate for smaller screen resolutions/DPI, but I'm not sure.

> Also, the option to check immediately for any streams is missing.

There is no option to manually check. The program will check periodically in the background. The refresh interval can be configured in the settings.

**Comment by 5ucur** [comment]
> Unfortunately your list is blurred.

I've blurred it to anonymise the follow list, as it's irrelevant. But you can see that the height is very large, easily covering too much of the screen height (1024) for just 23 list items, and putting the top of the list further from the panel icon than before. The profile pictures are 32x32, yes. 

> There is no option to manually check.

The screenshot in the [README.md](../blob/main/README.md) has the "Check now" option, as did the version of the program I used prior to updating it.
![screenshot-1](https://github.com/buzz/twitch-indicator/assets/28569802/bf97bdc3-c5aa-4b0e-814b-fc769fd7373c)

It's fine if both changes are here to stay, I only notified you of them in case they were unwanted occurrences as they deviated from the program's behaviour I was accustomed to. (apologies for my English, non-native speaker)
edited to fix typo

**Comment by buzz** [comment]
> I've blurred it to anonymise the follow list, as it's irrelevant.

I understand that you intentionally blurred the list. I think it's relevant as you specifically mentioned the channel list in your post.

> But you can see that the height is very large easily covering too much of the screen height (1024) for just 23 list items

The list takes as much screen space as it needs to display all the items in it. It depends on the specifics of your GTK theme how exactly it is rendered. I don't think it has anything to do with twitch-indicator tbh.

I don't know what I can do for you.

> The screenshot in the [README.md](https://github.com/buzz/twitch-indicator/blob/main/README.md) has the "Check now" option

I understand that the screenshot may be misleading. It's from 4 years ago, taken from a previous version of the program. I agree that it should be updated, but it's not a priority for me to work on currently...

**Comment by 5ucur** [comment]
Thanks, so in short these are not problems that need to be fixed. I'll look into how to set the GTK settings on KDE, as the list is too large sometimes to display all the items (there is scrolling). As there is nothing to be done, closing the issue.
