### ISSUE TITLE
Fails if game_id is missing

### ISSUE THREAD

**Issue by SCdF** [buzz/twitch-indicator#22]
Installed through arch pacman on EndevourOS (arch), running KDE 6.1.0 under Wayland.

When I first ran it the link with twitch window opened, and I did the linking, but then nothing else showed.

If I run it from a terminal I get this:

```
~ twitch-indicator 

(twitch-indicator:58637): Gtk-CRITICAL **: 17:07:12.215: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(twitch-indicator:58637): Gtk-CRITICAL **: 17:07:13.193: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/twitch_indicator/api/api_manager.py", line 151, in _on_validation_info_changed
    await self._refresh_live_streams()
  File "/usr/lib/python3.12/site-packages/twitch_indicator/api/api_manager.py", line 197, in _refresh_live_streams
    live_streams = await self.api.fetch_followed_streams(user_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/twitch_indicator/api/twitch_api.py", line 83, in fetch_followed_streams
    return ta_streams.validate_python(resp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pydantic/type_adapter.py", line 260, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for list[Stream]
10.game_id
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
```

And it hangs open, with no system tray indicator appearing.

Let me know if you want me to try anything.

**Comment by buzz** [comment]
It seems the Twitch API returned no `game_id` (`input_value=''`) when it should return an integer.

I have no idea why it does that, because it shouldn't according to the [reference](https://dev.twitch.tv/docs/api/reference/#get-followed-streams). Never experienced this. Could be a bug in the Twitch API.

Would be helpful to know which channel/game did that.

If this is happening more often, it might be necessary to make that field optional and provide some 'No game/category' placeholder for such cases.

**Comment by SCdF** [comment]
Is there some way I can turn on debugging locally or step through it? I can pull the repo down and try to dev on it to work it out, I'm not that familiar with python though. How easy is it for me to boot it from source with my credentials?

**Comment by SCdF** [comment]
Nevermind I hacked the gibson and just ripped the creds out of your code / .config and used it against curl.

It's the ghost of Giant Bomb past:

```
    {
      "id": "44406434347",
      "user_id": "218482369",
      "user_login": "giantbomb8",
      "user_name": "giantbomb8",
      "game_id": "",
      "game_name": "",
      "type": "live",
      "title": "Giant Bomb Infinite: Videos All Day, Videos All Night",
      "viewer_count": 48,
      "started_at": "2024-06-21T18:38:13Z",
      "language": "en",
      "thumbnail_url": "https://static-cdn.jtvnw.net/previews-ttv/live_user_giantbomb8-{width}x{height}.jpg",
      "tag_ids": [],
      "tags": ["English"],
      "is_mature": false
    },
```

**Comment by SCdF** [comment]
So unfollowing them it now no longer has that error, but on KDE 6 with Wayland it still doesn't create a visible system tray icon that I can find, and it still shows the GTK error:

```
➜  ~ twitch-indicator 

(twitch-indicator:109831): Gtk-CRITICAL **: 09:27:37.210: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(twitch-indicator:109831): Gtk-CRITICAL **: 09:27:38.224: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

```

I can try without wayland and see if that's the issue. Scale factor is a suspicious thing to complain about.

**Comment by SCdF** [comment]
Yep, it's wayland (as it always is lol). X11 works fine.

**Comment by buzz** [comment]
> It's the ghost of Giant Bomb past:

Thanks for figuring this out. [v1.8](https://github.com/buzz/twitch-indicator/releases/tag/1.8) should have this fixed.

> Yep, it's wayland

Sorry about that. This app just hasn't been tested at all on Wayland.
