### ISSUE TITLE
No longer able to find streams

### ISSUE THREAD

**Issue by CodyRude** [buzz/twitch-indicator#4]
Recently Twitch Indicator has stopped finding any streams. It looks like its failing to load my user id

`
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/twitch-indicator", line 329, in refresh_streams
    followed_channels = self.tw.fetch_followed_channels(self.USER_ID)
  File "/usr/bin/twitch-indicator", line 32, in fetch_followed_channels
    base_uri = TWITCH_API_URL + 'users/follows?from_id=' + user_id
TypeError: can only concatenate str (not "HTTPError") to str
`

**Comment by buzz** [comment]
Twitch made authentication mandatory as per now:
https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

Don't know when I'll manage to fix that. Patches welcome!

**Comment by alexandre1985** [comment]
It could be done to have a list of followed twitch channels on the computer/offline, instead of fetching the list of followers from https://twitch.tv .

**Comment by alexandre1985** [comment]
@CodyRude @buzz @bennyhillthebest In regards, to finding the streams, I have made a pull request that fixes this. https://github.com/buzz/twitch-indicator/pull/5 :wink: 

**update:** it seems the pull request was rejected and the code, now, has changed so much that my little python skills are unable to fix this issue.

**Comment by buzz** [comment]
Fixed in 1.0
